import pandas as pd
import numpy as np
import os
import xgboost as xgb
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix
from sklearn.model_selection import GroupKFold
import warnings
from models import make_xgb
from natsort import natsorted
warnings.filterwarnings('ignore')


'''
This script evaluates the overall performance of different models using a leave-one-group-out strategy. 
For example, when evaluating Group 1, we train the model on the combined data from Groups 2-15 and test on Group 1.
This process is repeated for each group, allowing us to assess how well the model generalizes to unseen groups.

The overall data table is expected to have the following columns:
MRN,StudyDate,group,available_phases,malignancy,feature1, feature2, ..., featureN

# However, we need to note that this evaluation need to use original data without oversampling, 
# otherwise some groups get really high performance because the samples in that group could be generated by oversampling, 
# which means the testing samples were also in the training set.

'''

if __name__ == "__main__":
    from config import DATA_ROOT_DIR
    all_normalized_data_fn = os.path.join(DATA_ROOT_DIR, "processed_data/grouped_instance_features_unified/all_groups_features_unified_normalized.csv")
    output_dir = os.path.join(DATA_ROOT_DIR, "processed_data/overall_eval")
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    performance_records = {"Group": [], "Accuracy": [], "AUC": [], "N_Test_Samples": [], "N_Train_Samples": []}
        
    # Load data
    try:
        df = pd.read_csv(all_normalized_data_fn)
        print(f"Loaded data with shape: {df.shape}")
    except Exception as e:
        print(f"Error loading {all_normalized_data_fn}: {e}")
    
    # Check required columns
    required_cols = ['MRN', 'StudyDate', 'group', 'available_phases', 'malignancy']
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        print(f"Missing required columns: {missing_cols}")
    
    # Identify feature columns (exclude metadata columns)
    feature_cols = [col for col in df.columns if col not in required_cols]
    print(f"Number of features: {len(feature_cols)}")
    
    # Check for missing values in features
    missing_features = df[feature_cols].isnull().sum().sum()
    if missing_features > 0:
        print(f"Warning: {missing_features} missing values in features")
    
    # Prepare features and target
    X = df[feature_cols].values
    y = df['malignancy'].values
    groups = df['group'].values
    
    print(f"Feature matrix shape: {X.shape}")
    print(f"Target distribution: {np.bincount(y)}")
    print(f"Number of groups: {len(np.unique(groups))}")
    
    # Leave-one-group-out cross-validation
    unique_groups = np.unique(groups)
    
    print("\nStarting leave-one-group-out evaluation...")
    
    for test_group in unique_groups:
        print(f"Testing on Group {test_group}...")
        
        # Split data
        test_mask = groups == test_group
        train_mask = ~test_mask
        
        X_train, X_test = X[train_mask], X[test_mask]
        y_train, y_test = y[train_mask], y[test_mask]
        
        # Check if test group has both classes
        if len(np.unique(y_test)) < 2:
            print(f"  Skipping Group {test_group} - only one class present in test set")
            continue
        
        # Check if training set has both classes
        if len(np.unique(y_train)) < 2:
            print(f"  Skipping Group {test_group} - only one class present in training set")
            continue
        
        print(f"  Train samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")
        print(f"  Train class dist: {np.bincount(y_train)}, Test class dist: {np.bincount(y_test)}")
        
        # Train XGBoost model
        try:
            # Calculate scale_pos_weight for class imbalance
            n_positive = np.sum(y_train == 1)
            n_negative = np.sum(y_train == 0)
            scale_pos_weight = n_negative / n_positive if n_positive > 0 else 1.0
            
            model = make_xgb(seed=42, scale_pos_weight=scale_pos_weight)
            model.fit(X_train, y_train)
            
            # Make predictions
            y_pred = model.predict(X_test)
            y_pred_proba = model.predict_proba(X_test)[:, 1]
            
            # Calculate metrics
            accuracy = accuracy_score(y_test, y_pred)
            auc = roc_auc_score(y_test, y_pred_proba)
            
            performance_records["Group"].append(test_group)
            performance_records["Accuracy"].append(accuracy)
            performance_records["AUC"].append(auc)
            performance_records["N_Test_Samples"].append(len(y_test))
            performance_records["N_Train_Samples"].append(len(y_train))
            
            print(f"  Accuracy: {accuracy:.4f}, AUC: {auc:.4f}")
            
        except Exception as e:
            print(f"  Error training model for Group {test_group}: {e}")
            continue
    

    # Save detailed group results
    group_df = pd.DataFrame(performance_records)
    group_csv = os.path.join(output_dir, f"XGBoost_leave_one_group_out_results.csv")
    # sort group_df by Group in natural order
    group_df["Group"] = group_df["Group"].astype(str)  # Ensure Group is string for sorting
    group_df = group_df.sort_values(by="Group", key=lambda x: natsorted(x))
    group_df.to_csv(group_csv, index=False)
    print(f"Detailed group results saved to: {group_csv}")
    







